In [1]:
import numpy as np


In [2]:
array = np.linspace(0,200,10)

In [3]:
array.shape


(10,)

In [4]:
array

array([  0.        ,  22.22222222,  44.44444444,  66.66666667,
        88.88888889, 111.11111111, 133.33333333, 155.55555556,
       177.77777778, 200.        ])

In [5]:
array = array.reshape(2,5)
array

array([[  0.        ,  22.22222222,  44.44444444,  66.66666667,
         88.88888889],
       [111.11111111, 133.33333333, 155.55555556, 177.77777778,
        200.        ]])

In [7]:
array[:,3]

array([ 66.66666667, 177.77777778])

In [9]:
arr = np. arange(0,15)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [10]:
np.mean(arr)

7.0

In [12]:
res = 7**4
res

2401

In [20]:
s = "Olá, Pai!"
t = s.split()
t
#type(t)

['Olá,', 'Pai!']

In [23]:
Planeta = "Terra"
Diametro = 12742
print("O diametro da {} é de {} kilometros.".format(Planeta,Diametro))

O diametro da Terra é de 12742 kilometros.


In [2]:
lst = [1,2,[3,4],[5,[100,200,['olá']],23,11],1,7]
lst

[1, 2, [3, 4], [5, [100, 200, ['olá']], 23, 11], 1, 7]

In [7]:
lst[3][1][2][0]

'olá'

In [12]:
def obterDominio(email):
    res = email.split('@')[-1]# -1 Sempre pega o ultimo elemento
    print(res)
    return res[1]

In [13]:
print(obterDominio('user@domain.com'))

['user', 'domain.com']
domain.com


In [15]:
encontreCachorro("Existe um cachorro ai?")

True

In [14]:
def encontreCachorro(string):
    return 'cachorro' in string.lower()

In [29]:
contaCachorro('Esse cachorro é mais rápido que o outro cachorro ')

esse
cachorro
é
mais
rápido
que
o
outro
cachorro


2

In [30]:
def contaCachorro(string):
    cont = 0
    for i in string.lower().split():
        if(i == 'cachorro'):
            cont= cont + 1
    return cont